### ISSUE TITLE
Implement Parser for MONDO Data with OBO Tree Structure Integration

### ISSUE THREAD

**Issue by themkdemiiir** [cdliproject/Prometheus#4]
Our project entails developing a parser for integrating the MONDO (Mendelian Ontology) dataset into our system, focusing on preserving the OBO (Open Biological and Biomedical Ontology) information tree structure. The MONDO dataset, detailed on their [download page](https://mondo.monarchinitiative.org/pages/download/), offers a comprehensive ontology for human diseases, aiming to align various disease resources into a unified format. An essential aspect of this integration is maintaining the hierarchical tree structure of the OBO format, which is crucial for the accurate representation and analysis of the data. This integration will significantly enhance our system's ability to process complex disease information, supporting advanced research and analysis capabilities. The parser will be tailored to handle the diverse data formats provided by MONDO and retain the integrity of the OBO tree structure.

Task Checklist:

- [x] Thoroughly analyze the MONDO data formats, focusing on the OBO tree structure.
- [x] Design a parser architecture that supports and maintains the OBO tree structure within MONDO data.
- [x] Develop the parser code, ensuring accuracy in processing and integrating data while preserving the OBO hierarchy.
- [ ] Test the parser with MONDO data samples to ensure the tree structure is correctly maintained.
- [ ] Seamlessly integrate the parser into our existing system, maintaining data integrity and structure.
- [ ] Could you perform extensive testing to ensure stability, performance, and accuracy in the representation of the OBO tree structure?
- [ ] Document the process and update user manuals, highlighting the preservation of the OBO tree structure in the MONDO data integration.

**Comment by Simurgan** [comment]
I have implemented a parser for mondo owl file.
Currently the annotations and the relationships cannot be parsed. I will implement them later.
By relationship, the parentclassing and the subclasing are not meant.
The ontology hierarchy graph can be parsed entirely in the current version.

Currently, I have not tested the code yet.
I will test the code in a detailed and deeper manner later since testing in such huge files is so hard and time consuming.
Current development can be found in [this commit](https://github.com/cdliproject/Prometheus/tree/c254ecb5712a98712cc97f054814717d7ee33e15) of [mondo branch](https://github.com/cdliproject/Prometheus/tree/mondo).

**Comment by Simurgan** [comment]
Currently I am getting a "TypeError: unhashable type: 'Entity'" while testing.
I will solve this problem later.
